pipeline {
    agent {
        docker  {
            image 'javasbapp'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo "Hello Word"
                sh 'java -version'
				sh 'curl -v http://34.207.127.202:8081/artifactory'
                sh 'mvn -f demo/pom.xml clean install'
                curl -u admin:admin -T /root/.m2/repository/com/example/demo/0.0.1-SNAPSHOT/demo-0.0.1-SNAPSHOT.jar "http://localhost:8081/artifactory/libs-release-local/domo/"
					
				}
            }
        }
    }
}
